name: index

on:
  workflow_dispatch:
  
  schedule:
    # UTC 时间
     - cron: "2 0,4,12 * * *"    
  watch: 
      types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp
        pip install requests
    - name: Run
      env:
          aabb: ${{ secrets.aabb }}
          bbaa: ${{ secrets.bbaa }}
      run: |
        python index.py
